# Generated by Django 5.2.7 on 2025-11-07 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('lecturer', 'Lecturer'), ('admin', 'Administrator')], default='student', max_length=20)),
                ('department', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Computer Software Engineering', 'Computer Software Engineering'), ('Computer Engineering', 'Computer Engineering'), ('Computer Hardware', 'Computer Hardware'), ('Accountancy', 'Accountancy')], default='Computer Science', max_length=100)),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
