# Generated by Django 5.2.7 on 2025-11-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_delete_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('department', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Computer Software Engineering', 'Computer Software Engineering'), ('Computer Engineering', 'Computer Engineering'), ('Computer Hardware', 'Computer Hardware'), ('Accountancy', 'Accountancy')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Computer Software Engineering', 'Computer Software Engineering'), ('Computer Engineering', 'Computer Engineering'), ('Computer Hardware', 'Computer Hardware'), ('Accountancy', 'Accountancy')], max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('lecturer', 'Lecturer'), ('admin', 'Administrator')], max_length=50),
        ),
    ]
