# Generated by Django 5.2.6 on 2025-11-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_course_alter_profile_department_alter_profile_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('Computer Software Engineering', 'Computer Software Engineering'), ('Computer Science', 'Computer Science'), ('Computer Hardware Engineering', 'Computer Hardware Engineering'), ('Computer Engineering', 'Computer Engineering'), ('Accountancy', 'Accountancy'), ('Networking', 'Networking')], default='Computer Science', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('lecturer', 'Lecturer'), ('admin', 'Administrator')], default='student', max_length=20),
        ),
    ]
