# Generated by Django 5.2.6 on 2025-11-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
    ]
