# Generated by Django 5.2.7 on 2025-12-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_profile_profile_image_alter_assignment_lecturer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='client_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='status',
            field=models.CharField(default='sent', max_length=20),
        ),
    ]
